name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Or the branch you're working on, e.g., master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Git
      run: |
        git config --global user.name "github-actions"
        git config --global user.email "github-actions@github.com"

    - name: Create gh-pages branch if it does not exist
      run: |
        git fetch origin gh-pages || echo "No gh-pages branch yet"
        git checkout -b gh-pages || git checkout gh-pages

    - name: Copy files to GitHub Pages folder
      run: |
        mkdir -p gh-pages
        cp -r Deploy/Fiesta/* gh-pages/

    - name: Commit and push changes
      run: |
        cd gh-pages
        git add .
        git commit -m "Deploy site to GitHub Pages" || echo "No changes to commit"
        git push origin gh-pages --force
