name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Or the branch you're working on, e.g., master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Git
      run: |
        git config --global user.name "github-actions"
        git config --global user.email "github-actions@github.com"

    - name: Copy files to GitHub Pages folder
      run: |
        mkdir -p gh-pages
        cp -r Deploy/Fiesta/* gh-pages/

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./gh-pages
        publish_branch: gh-pages  # This is the default branch for GitHub Pages
