name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Change this if you're using a different default branch

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Pages
        uses: actions/configure-pages@v3

      - name: Upload Artifact (Only Deploy Folder)
        uses: actions/upload-pages-artifact@v4  # Updated to v4
        with:
          name: deploy-artifact  # Can be any name you'd like
          path: Deploy/Fiesta  # Using relative path from the root of the repo

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
